SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `gsb_visiteurs`.`famille` CHANGE COLUMN `FAM_CODE` `FAM_CODE` VARCHAR(3) NOT NULL  
, ADD PRIMARY KEY (`FAM_CODE`) ;

ALTER TABLE `gsb_visiteurs`.`inviter` CHANGE COLUMN `AC_NUM` `AC_NUM` INT(11) NOT NULL  , CHANGE COLUMN `PRA_NUM` `PRA_NUM` SMALLINT(6) NOT NULL  
, ADD PRIMARY KEY (`AC_NUM`, `PRA_NUM`) 
, ADD INDEX `fk_inviter_activite_compl1_idx` (`AC_NUM` ASC) 
, ADD INDEX `fk_inviter_praticien1_idx` (`PRA_NUM` ASC) ;

ALTER TABLE `gsb_visiteurs`.`medicament` CHANGE COLUMN `MED_DEPOTLEGAL` `MED_DEPOTLEGAL` VARCHAR(10) NOT NULL  , ADD COLUMN `MED_PRESENTATION` VARCHAR(45) NULL DEFAULT NULL  AFTER `MED_PRIXECHANTILLON` 
, ADD PRIMARY KEY (`MED_DEPOTLEGAL`) 
, ADD INDEX `fk_medicament_famille1_idx` (`FAM_CODE` ASC) ;

ALTER TABLE `gsb_visiteurs`.`offrir` CHANGE COLUMN `VIS_MATRICULE` `VIS_MATRICULE` VARCHAR(10) NOT NULL  , CHANGE COLUMN `RAP_NUM` `RAP_NUM` INT(11) NOT NULL  , CHANGE COLUMN `MED_DEPOTLEGAL` `MED_DEPOTLEGAL` VARCHAR(10) NOT NULL   
, ADD PRIMARY KEY (`VIS_MATRICULE`, `RAP_NUM`, `MED_DEPOTLEGAL`) 
, ADD INDEX `fk_offrir_rapport_visite1_idx` (`VIS_MATRICULE` ASC) 
, ADD INDEX `fk_offrir_rapport_visite2_idx` (`RAP_NUM` ASC) 
, ADD INDEX `fk_offrir_medicament1_idx` (`MED_DEPOTLEGAL` ASC) ;

ALTER TABLE `gsb_visiteurs`.`posseder` CHANGE COLUMN `PRA_NUM` `PRA_NUM` SMALLINT(6) NOT NULL  , CHANGE COLUMN `SPE_CODE` `SPE_CODE` VARCHAR(5) NOT NULL  
, ADD PRIMARY KEY (`PRA_NUM`, `SPE_CODE`) 
, ADD INDEX `fk_posseder_specialite1_idx` (`SPE_CODE` ASC) 
, ADD INDEX `fk_posseder_praticien1_idx` (`PRA_NUM` ASC) ;

ALTER TABLE `gsb_visiteurs`.`praticien` CHANGE COLUMN `PRA_NUM` `PRA_NUM` SMALLINT(6) NOT NULL  
, ADD PRIMARY KEY (`PRA_NUM`) 
, ADD INDEX `fk_praticien_type_praticien1_idx` (`TYP_CODE` ASC) ;

ALTER TABLE `gsb_visiteurs`.`prescrire` CHANGE COLUMN `MED_DEPOTLEGAL` `MED_DEPOTLEGAL` VARCHAR(10) NOT NULL  , CHANGE COLUMN `TIN_CODE` `TIN_CODE` VARCHAR(5) NOT NULL   , CHANGE COLUMN `DOS_CODE` `DOS_CODE` VARCHAR(10) NOT NULL   
, ADD PRIMARY KEY (`MED_DEPOTLEGAL`, `TIN_CODE`, `DOS_CODE`) 
, ADD INDEX `fk_prescrire_medicament1_idx` (`MED_DEPOTLEGAL` ASC) 
, ADD INDEX `fk_prescrire_type_individu1_idx` (`TIN_CODE` ASC) 
, ADD INDEX `fk_prescrire_dosage1_idx` (`DOS_CODE` ASC) ;

ALTER TABLE `gsb_visiteurs`.`rapport_visite` CHANGE COLUMN `VIS_MATRICULE` `VIS_MATRICULE` VARCHAR(10) NOT NULL  , CHANGE COLUMN `RAP_NUM` `RAP_NUM` INT(11) NOT NULL   
, ADD PRIMARY KEY (`VIS_MATRICULE`, `RAP_NUM`) 
, ADD INDEX `fk_rapport_visite_praticien1_idx` (`PRA_NUM` ASC) 
, ADD INDEX `fk_rapport_visite_visiteur1_idx` (`VIS_MATRICULE` ASC) ;

ALTER TABLE `gsb_visiteurs`.`realiser` CHANGE COLUMN `AC_NUM` `AC_NUM` INT(11) NOT NULL  , CHANGE COLUMN `VIS_MATRICULE` `VIS_MATRICULE` VARCHAR(10) NOT NULL   
, ADD PRIMARY KEY (`AC_NUM`, `VIS_MATRICULE`) 
, ADD INDEX `fk_realiser_visiteur1_idx` (`VIS_MATRICULE` ASC) 
, ADD INDEX `fk_realiser_activite_compl1_idx` (`AC_NUM` ASC) ;

ALTER TABLE `gsb_visiteurs`.`region` CHANGE COLUMN `REG_CODE` `REG_CODE` VARCHAR(2) NOT NULL  
, ADD PRIMARY KEY (`REG_CODE`) 
, ADD INDEX `fk_region_secteur_idx` (`SEC_CODE` ASC) ;

ALTER TABLE `gsb_visiteurs`.`secteur` CHANGE COLUMN `SEC_CODE` `SEC_CODE` VARCHAR(1) NOT NULL  
, ADD PRIMARY KEY (`SEC_CODE`) ;

ALTER TABLE `gsb_visiteurs`.`specialite` CHANGE COLUMN `SPE_CODE` `SPE_CODE` VARCHAR(5) NOT NULL  
, ADD PRIMARY KEY (`SPE_CODE`) ;

ALTER TABLE `gsb_visiteurs`.`travailler` CHANGE COLUMN `VIS_MATRICULE` `VIS_MATRICULE` VARCHAR(10) NOT NULL  , CHANGE COLUMN `JJMMAA` `JJMMAA` DATETIME NOT NULL   , CHANGE COLUMN `REG_CODE` `REG_CODE` VARCHAR(2) NOT NULL  
, ADD PRIMARY KEY (`VIS_MATRICULE`, `JJMMAA`, `REG_CODE`) 
, ADD INDEX `fk_travailler_visiteur1_idx` (`VIS_MATRICULE` ASC) 
, ADD INDEX `fk_travailler_region1_idx` (`REG_CODE` ASC) ;

ALTER TABLE `gsb_visiteurs`.`type_individu` CHANGE COLUMN `TIN_CODE` `TIN_CODE` VARCHAR(5) NOT NULL  
, ADD PRIMARY KEY (`TIN_CODE`) ;

ALTER TABLE `gsb_visiteurs`.`type_praticien` CHANGE COLUMN `TYP_CODE` `TYP_CODE` VARCHAR(3) NOT NULL  
, ADD PRIMARY KEY (`TYP_CODE`) ;

ALTER TABLE `gsb_visiteurs`.`visiteur` CHANGE COLUMN `VIS_MATRICULE` `VIS_MATRICULE` VARCHAR(10) NOT NULL  
, ADD PRIMARY KEY (`VIS_MATRICULE`) 
, ADD INDEX `fk_visiteur_labo1_idx` (`LAB_CODE` ASC) 
, ADD INDEX `fk_visiteur_secteur1_idx` (`SEC_CODE` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
